### ISSUE TITLE
Use production settings as default in Helm chart

### ISSUE THREAD

**Issue by microamp** [ietf-tools/www#436]
It's better to use `ietf.settings.production` (where `DEBUG` is `False`) in both staging and prod.

**Comment by rjsparks** [comment]
Note that this is only ok (as in not dangerous) because the runtime code currently has no switches based on a notion of "am I in production or not" as the datatracker does. If such code ever comes in (to our extensions, or into wagtail, (or maybe we haven't discovered it in wagtail)), unintended unpleasant consequences become _very_ likely.
